{{- $template := fromYaml (include "raw.resource" .) -}}
{{- range $i, $t := .Values.resources }}
---
{{ toYaml (merge $t $template) -}}
{{- end }}
{{- range $i, $t := .Values.templates }}
---
{{ toYaml (merge (tpl $t $ | fromYaml) $template) -}}
{{- end }}
