{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    helm.sh/chart: {{ template "pgbouncer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}    
spec:
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}      
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "15s" }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels | default true }}
      relabelings:
      {{- if .Values.serviceMonitor.relabelings }}
      {{- toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
      {{- end }}  
  {{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
  {{- range .Values.serviceMonitor.targetLabels }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- if .Values.serviceMonitor.sampleLimit }}
  sampleLimit: {{ .Values.serviceMonitor.sampleLimit }}   
  {{- end }}     
{{- end }}
